### ISSUE TITLE
sample_vin running failed,I2C failed,also no video data received.

### ISSUE THREAD

**Issue by zlyadvocate** [AXERA-TECH/ax620q_bsp_sdk#2]
when running on Zero，it failed:
I2C failed,also no video data received.
/opt/bin # ./sample_vin  -c 3
[COMM_ISP][main][ 1010] VIN Sample. Build at Apr 19 2024 02:22:56
[COMM_ISP][__sample_case_config][  680] eSysCase 3, eSysMode 1, eHdrMode 1, bAiispEnable 0
[COMM_ISP][__sample_case_single_sc450ai][  475] error sys mode : __sample_case_single_sc450ai
[COMM_ISP][__sample_case_single_sc450ai][  481] error sys mode : COMMON_VIN_GetSnsConfig
AX_POOL_SetConfig success!
[COMM_SYS][               COMMON_SYS_Init][  101] AX_POOL_Init success!
AX_VIN_SetPoolAttr success!
[COMM_ISP][COMMON_ISP_RegisterSns][  196] set sensor bus idx 0
[COMM_ISP][COMMON_ISP_RegisterSns][  208] set sensor slave addr 48
i2c_init: i2c device is /dev/i2c-0 
i2c_read: Failed to read reg: Remote I/O error.!
i2c_read: Failed to read reg: Remote I/O error.!
i2c_write: Failed to write reg: Remote I/O error.!
i2c_write: Failed to write reg: Remote I/O error.!
i2c_write: Failed to write reg: Remote I/O error.!
i2c_write: Failed to write reg: Remote I/O error.!
Detect I2C is 
/opt # i2cdetect  -y 6
i2cdetect: warning: can't use SMBus quick write command, will skip some addresses
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                                                 
10:                                                 
20:                                                 
30: 30 -- -- -- -- -- -- --                         
40:                                                 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60:                                                 
70:

**Comment by zlyadvocate** [comment]
all other sample related to vin also failed.

**Comment by BUG1989** [comment]
For zero branch, we will quickly provide

**Comment by BUG1989** [comment]
@zlyadvocate https://github.com/AXERA-TECH/ax620q_bsp_sdk/tree/v1.7.0-zero This branch fixd it.
