### ISSUE TITLE
sample_vin_ivps_venc_rtsp run wrong.Slave address is mistake.changed to 0x30,also failed.

### ISSUE THREAD

**Issue by zlyadvocate** [AXERA-TECH/ax620q_bsp_sdk#3]
/opt/bin # ./sample_vin_ivps_venc_rtsp -c 3 -r 1
INFO   :[main:1213] VIN Sample. Build at Apr 24 2024 18:11:04
INFO   :[__sample_case_config:362] eSysCase 3, eSysMode 1, eLoadRawNode -1, eHdrMode 1, bAiispEnable 0
[COMM_ISP][COMMON_ISP_GetSnsObj][  127] open /opt/lib/libsns_sc450ai.so fail!zly ---(null)
AX_POOL_SetConfig success!
[COMM_SYS][               COMMON_SYS_Init][  101] AX_POOL_Init success!
INFO   :[SAMPLE_VENC_Init:630] VencChn 0:w:2688, h:1520, s:2688, rcType:0, payload:96
INFO   :[SAMPLE_VENC_Init:630] VencChn 1:w:1920, h:1080, s:1920, rcType:0, payload:96
INFO   :[SAMPLE_VENC_Init:630] VencChn 2:w:720, h:576, s:720, rcType:0, payload:96
AX_VIN_SetPoolAttr success!
[COMM_ISP][COMMON_ISP_RegisterSns][  197] set sensor bus idx 6
[COMM_ISP][COMMON_ISP_RegisterSns][  209] set sensor slave addr 0
i2c_init: i2c device is /dev/i2c-6 
[COMM_ISP][COMMON_ISP_RegisterAeAlgLib][  289] bUser3a 0
[COMM_CAM][COMMON_CAM_Open][  352] camera 0 is open
[ COMM_NT][COMMON_NT_Init][   28] Start the service on the tuning device side.
port = 6000,  socketfd_listen = 30
port = 8082,  socketfd_listen = 31
[ COMM_NT][COMMON_NT_Init][   41] NT Stream Listen Port 6000.
[ COMM_NT][COMMON_NT_Init][   42] NT Ctrl Listen Port 8082.
chn 0, src 2688x1520, img_fmt 80
INFO   :[SampleRtspInit:988] RTSP pRtspHandle:0x14a870 nChnNum:3

change to 0x30

/opt/bin # ./sample_vin_ivps_venc_rtsp -c 3 -r 1
INFO   :[main:1213] VIN Sample. Build at Apr 24 2024 18:11:04
INFO   :[__sample_case_config:362] eSysCase 3, eSysMode 1, eLoadRawNode -1, eHdrMode 1, bAiispEnable 0
[COMM_ISP][COMMON_ISP_GetSnsObj][  127] open /opt/lib/libsns_sc450ai.so fail!zly ---(null)
AX_POOL_SetConfig success!
[COMM_SYS][               COMMON_SYS_Init][  101] AX_POOL_Init success!
INFO   :[SAMPLE_VENC_Init:630] VencChn 0:w:2688, h:1520, s:2688, rcType:0, payload:96
INFO   :[SAMPLE_VENC_Init:630] VencChn 1:w:1920, h:1080, s:1920, rcType:0, payload:96
INFO   :[SAMPLE_VENC_Init:630] VencChn 2:w:720, h:576, s:720, rcType:0, payload:96
AX_VIN_SetPoolAttr success!
[COMM_ISP][COMMON_ISP_RegisterSns][  197] set sensor bus idx 6
[COMM_ISP][COMMON_ISP_RegisterSns][  210] set sensor slave addr 48
i2c_init: i2c device is /dev/i2c-6 
[COMM_ISP][COMMON_ISP_RegisterAeAlgLib][  290] bUser3a 0
[COMM_CAM][COMMON_CAM_Open][  352] camera 0 is open

**Comment by BUG1989** [comment]
please use the branch of zero
